<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite ignored="0" hostname="DESKTOP-OI1TN93" failures="0" tests="7" name="com.testing.features.Credentials" time="0.019" errors="1" timestamp="06 Jan 2022 06:48:35 GMT" skipped="5">
  <testcase classname="com.testing.features.Credentials" name="password" time="0.001">
    <skipped/>
  </testcase> <!-- password -->
  <testcase classname="com.testing.features.Credentials" name="password" time="0.001">
    <error message="expected:&lt;m...&gt; but was:&lt;M...&gt;" type="junit.framework.ComparisonFailure">
      <![CDATA[junit.framework.ComparisonFailure: expected:<m...> but was:<M...>
	at junit.framework.Assert.assertEquals(Assert.java:81)
	at junit.framework.Assert.assertEquals(Assert.java:87)
	at com.testing.features.Credentials.password(Credentials.java:21)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:998)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1200)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- password -->
  <testcase classname="com.testing.features.Credentials" name="password" time="0.004">
    <skipped/>
  </testcase> <!-- password -->
  <testcase classname="com.testing.features.Credentials" name="password" time="0.010">
    <skipped/>
  </testcase> <!-- password -->
  <testcase classname="com.testing.features.Credentials" name="password" time="0.001">
    <skipped/>
  </testcase> <!-- password -->
  <testcase classname="com.testing.features.Credentials" name="username" time="0.001"/>
  <testcase classname="com.testing.features.Credentials" name="password" time="0.001">
    <skipped/>
  </testcase> <!-- password -->
</testsuite> <!-- com.testing.features.Credentials -->
